# Generated by Django 4.1.5 on 2023-02-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_project_project_users_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_users',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_users',
            new_name='members',
        ),
    ]
